### ISSUE TITLE
Issue in back office after installation of the module

### ISSUE THREAD

**Issue by Wevar** [taoufiqaitali/prestashop-phone-field-for-registration#2]
Hello, first of all I wanted to thank you for the work you have done in developing this module. Unfortunately I have a problem using it.
I did as instructed and installed the module, so the phone field is added to my form correctly.

But when I go back to the backOffice, in the SELL -> Customers section, I have the following error: "The server returned a" 500 Internal Server Error "."

Do you have any idea where this might come from?

Thank you!

**Comment by taoufiqaitali** [comment]
@Wevar thanks for your support
can you enable debug mode in prestashop and send details about error message

+ log file?
+ what version you have?

**Comment by Wevar** [comment]
I'm sending you the screen shot of the logfile.

I got prestashop 1.7.6.2

Le ven. 30 oct. 2020 à 17:23, Taoufiq Ait Ali <notifications@github.com> a
écrit :

**Comment by Wevar** [comment]
Hello, so do you know why this problem is happening? I still didn't figure out

**Comment by taoufiqaitali** [comment]
Hi, you forget to attach screenshot

**Comment by Wevar** [comment]
Yes im sorry, i sent it on gmail and didn't know that it doesn't work on github. here it is.
[Uploading screencapture-biscuits-charly-fr-admin448bv5gwp-index-php-sell-customers-2020-10-30-17_29_54 (1).pdf…]()

**Comment by Wevar** [comment]
You are right, sorry i thought that i could send it via gmail and that you would receive it here. Here it is
[screencapture-biscuits-charly-fr-admin448bv5gwp-index-php-sell-customers-2020-10-30-17_29_54 (1).pdf](https://github.com/taoufiqaitali/prestashop-phone-field-for-registration/files/5484537/screencapture-biscuits-charly-fr-admin448bv5gwp-index-php-sell-customers-2020-10-30-17_29_54.1.pdf)

**Comment by taoufiqaitali** [comment]
@Wevar go to position in backoffice
remove module from these two hooks and check if it will work 
hookActionCustomerGridDefinition and hookActionCustomerGridQueryBuilder

**Comment by Wevar** [comment]
Hello, it seems to work perfectly now ! Thank you very much !
