### ISSUE TITLE
Change field order 

### ISSUE THREAD

**Issue by ikt27** [taoufiqaitali/prestashop-phone-field-for-registration#3]
Hi !

Thank you for the awesome module, I have been looking for a solution for hours.

The module works well but I have one question (I hope it's the right spot to post this question) : 
When you add a new field, it appears last in the registration form.
Is it possible to choose the order in which the fields appear?

![image](https://user-images.githubusercontent.com/91728679/135600596-4668894f-5c03-49f2-ac41-d014ac2f52e9.png)

**Comment by taoufiqaitali** [comment]
Hi @ikt27, sorry for late reply
in order to change the position for the field, you have to overrid this file classes/form/CustomerFormatter.php
and change the position for the hook "additionalCustomerFormFields" or create new hook position and assign module to it
