### ISSUE TITLE
choosing the position in form

### ISSUE THREAD

**Issue by comodino** [taoufiqaitali/prestashop-phone-field-for-registration#4]
Hi, good job; is possible to change the position in form? for example after the email? 
i saw that the hook is positioned to bottom
thanks

**Comment by taoufiqaitali** [comment]
Hi @comodino,  thanks
in order to change the position for the field, you have to overrid this file classes/form/CustomerFormatter.php
and change the position for the hook "additionalCustomerFormFields" or create new hook position and assign module to it

**Comment by comodino** [comment]
thanls, i have creted override:

`<?php
/**
 * @Override CustomerFormatter
 */
use Symfony\Component\Translation\TranslatorInterface;

class CustomerFormatter extends CustomerFormatterCore
{

    private $translator;
    private $language;

    public function __construct(
        TranslatorInterface $translator,
        Language $language
    ) {
        parent::__construct($translator, $language);
        $this->translator = $translator;
        $this->language = $language;
    }

    public function getFormat()
    {
        $format = parent::getFormat();

        $format = [];

        // New Field added Here --------------------------------------->
        $format['phone'] = (new FormField)
            ->setName('phone')
            ->setLabel(
                $this->translator->trans(
                    'Phone', [], 'Shop.Forms.Labels'
                )
            )
            ->setRequired(true);
        //End Of here ------------------------------------------------------>
    }

}`

and commented this:
`    public function hookAdditionalCustomerFormFields($params)
    {/*
        $formField = new FormField();
        $formField->setName('phone');
        $formField->setType('text');
        $formField->setLabel($this->l('Phone'));
        $formField->setRequired(true);
        return array($formField);*/
    }`

but don't appear

**Comment by taoufiqaitali** [comment]
You added it to override in prestashop folder?! Cleared cache??
If you added it to override folder in module you have to uninstall
and reinstall module again

**Comment by comodino** [comment]
in module folder....i have unistall and reinstall but i don't see in form...

**Comment by comodino** [comment]
[regphonefield.zip](https://github.com/taoufiqaitali/prestashop-phone-field-for-registration/files/8165078/regphonefield.zip)
in this i move the entire file CustomerFormatter in folder override form (and add new field)
