### ISSUE TITLE
How can I move the field

### ISSUE THREAD

**Issue by tecnopaks** [taoufiqaitali/prestashop-phone-field-for-registration#8]
How can I move the field below the birthday field and above the terms and conditions.

**Comment by msjoker** [comment]
> How can I move the field below the birthday field and above the terms and conditions.

Hi!, did you make it?

**Comment by tecnopaks** [comment]
> > How can I move the field below the birthday field and above the terms and conditions.
> 
> Hi!, did you make it?

sorry no

**Comment by taoufiqaitali** [comment]
check this issue  https://github.com/taoufiqaitali/prestashop-phone-field-for-registration/issues/4#issuecomment-1055792355

already mentioned steps
